export {
    ScratchDiagnosticError,
    createScratchDiagnostic,
    createScratchDiagnosticReport,
    throwScratchDiagnostic,
} from './gpu/diagnostics.js'
export type {
    DiagnosticSubject,
    ScratchDiagnostic,
    ScratchDiagnosticInput,
    ScratchDiagnosticReport,
} from './gpu/diagnostics.js'
export type {
    GpuAttributionConfidence,
    GpuDescriptorEvidence,
    GpuNativeErrorCategory,
    GpuOperationKind,
    GpuOperationStatus,
    ScratchGpuIncidentEvidenceCompleteness,
    ScratchGpuIncidentKind,
    ScratchGpuIncidentFailureStage,
    ScratchGpuIncidentOutcome,
    ScratchGpuIncidentTarget,
    ScratchGpuIncidentReport,
    ScratchGpuCommandOperationRecord,
    ScratchGpuCommandOperationTarget,
    ScratchGpuBindLayoutOperationRecord,
    ScratchGpuBindLayoutOperationTarget,
    ScratchGpuBindSetOperationRecord,
    ScratchGpuBindSetOperationTarget,
    ScratchGpuBindSetPreparationStage,
    ScratchGpuBufferMappingIncidentReport,
    ScratchBufferMappingFailureStage,
    ScratchGpuContentResourceOperationTarget,
    ScratchGpuOperationRecord,
    ScratchGpuOperationTarget,
    ScratchGpuPipelineFailureStage,
    ScratchGpuPipelineOperationRecord,
    ScratchGpuPipelineOperationTarget,
    ScratchGpuPressureContributor,
    ScratchGpuPressureEvidence,
    ScratchGpuResourceOperationRecord,
    ScratchGpuResourceOperationTarget,
    ScratchGpuShaderModuleOperationRecord,
    ScratchGpuShaderModuleOperationTarget,
    ScratchGpuSamplerOperationTarget,
    ScratchGpuQuerySetOperationTarget,
    ScratchGpuQuerySetSlotFact,
    ScratchGpuReadbackIncidentReport,
    ScratchGpuReadbackOperationRecord,
    ScratchGpuReadbackOperationTarget,
    ScratchGpuRenderBundleOperationRecord,
    ScratchGpuRenderBundleOperationTarget,
    ScratchGpuRuntimeIncidentTarget,
    ScratchGpuSubmissionIncidentReport,
    ScratchGpuSubmissionOperationRecord,
    ScratchGpuSubmissionOperationTarget,
    ScratchReadbackFailureStage,
    ScratchReadbackNativeOutcome,
    ScratchReadbackNativeOutcomeFact,
    ScratchReadbackNativeOutcomeInput,
    ScratchReadbackNativeStage,
    ScratchSubmissionFailureStage,
    ScratchSubmissionNativeLocation,
    ScratchSubmissionNativeOutcome,
    ScratchSubmissionNativeOutcomeFact,
    ScratchSubmissionNativeOutcomeInput,
    ScratchSubmissionNativeOutcomeMode,
    ScratchSubmissionNativeOutcomeStatus,
    ScratchSubmissionNativeStage,
    ScratchSubmissionQueueActionKind,
    ScratchSubmissionScopeMode,
    ScratchPipelineNativeLabelEvidence,
    ScratchPipelineNativeLabelFact,
    ScratchNativeGpuErrorFacts,
    ScratchGpuSupportingObjectIncidentReport,
    ScratchSupportingObjectFailureStage,
} from './gpu/gpu-operation.js'
export type {
    PipelineCreationReport,
    PipelineCreationStageFact,
    PipelineKind,
    ShaderModuleCompilationMessage,
    ShaderModuleCompilationNativeLocation,
    ShaderModuleCompilationReport,
    ShaderModuleCompilationSourcePartFact,
    ShaderModuleCompilationSourcePartLocation,
} from './gpu/pipeline-compilation.js'
export { ScratchRuntime } from './gpu/runtime.js'
export type {
    ScratchAdapterInfoSnapshot,
    ScratchFeatureLevel,
    ScratchRuntimeAdapterRequestFacts,
    ScratchRuntimeCreateOptions,
    ScratchRuntimeDeviceRequestFacts,
    ScratchRuntimeRequestFacts,
} from './gpu/runtime.js'
export type { ScratchReadbackOptions, ScratchReadbackPolicy } from './gpu/readback-ownership.js'
export { ScratchDiagnosticCapture, ScratchRuntimeDiagnostics } from './gpu/runtime-diagnostics.js'
export type {
    ScratchReadbackCommandState,
    ScratchDeviceLostInfo,
    ScratchDiagnosticCaptureOptions,
    ScratchDiagnosticCaptureReport,
    ScratchDiagnosticCaptureStopReason,
    ScratchGpuIncidentQuery,
    ScratchGpuOperationQuery,
    ScratchPendingGpuOperationFact,
    ScratchRuntimeDiagnosticsOptions,
    ScratchRuntimeDiagnosticsEvidence,
    ScratchRuntimeDiagnosticsSnapshot,
    ScratchRuntimePipelineFact,
    ScratchRuntimeBindLayoutFact,
    ScratchRuntimeBindSetFact,
    ScratchRuntimeContentResourceFact,
    ScratchRuntimeSamplerResourceFact,
    ScratchRuntimeQuerySetResourceFact,
    ScratchRuntimeReadbackCommandFact,
    ScratchRuntimeReadbackOperationFact,
    ScratchRuntimeBufferMappingFact,
    ScratchRuntimeResourceFact,
} from './gpu/runtime-diagnostics.js'
export { Surface } from './gpu/surface.js'
export type { SurfaceFormat, SurfaceOptions, SurfaceSize } from './gpu/surface.js'
export {
    ExternalTextureBinding,
    SurfaceTextureLease,
    SurfaceTextureView,
} from './gpu/temporal-texture.js'
export type {
    ExternalTextureBindingDescriptor,
    SurfaceTextureLeaseState,
} from './gpu/temporal-texture.js'
export { Resource } from './gpu/resource.js'
export type { ResourceState } from './gpu/resource.js'
export { BufferRegion, BufferResource } from './gpu/buffer.js'
export type {
    BufferRegionDescriptor,
    BufferResourceDescriptor,
    BufferSubregionDescriptor,
    MappedBufferResourceDescriptor,
} from './gpu/buffer.js'
export { MappedBufferLease } from './gpu/buffer-mapping.js'
export type {
    BufferMappingDescriptor,
    BufferMappingMode,
    MappedBufferCreation,
    MappedBufferLeaseState,
} from './gpu/buffer-mapping.js'
export { TextureResource, TextureViewSpec } from './gpu/texture.js'
export type {
    NormalizedTextureViewDescriptor,
    TextureResourceDescriptor,
    TextureResourceSize,
    TextureViewDescriptor,
} from './gpu/texture.js'
export { SamplerResource } from './gpu/sampler.js'
export type { SamplerResourceDescriptor } from './gpu/sampler.js'
export { QuerySetResource } from './gpu/query-set.js'
export type {
    QuerySetResourceDescriptor,
    QuerySetSlotSnapshot,
    QuerySetSlotState,
    QuerySetType,
} from './gpu/query-set.js'
export { BindLayout, BindSet } from './gpu/binding.js'
export type {
    BindLayoutDescriptor,
    BindLayoutEntry,
    BindSetBindingResource,
    BindSetBindings,
    BindSetOptions,
    BindSetPreparationState,
    BindVisibility,
    ExternalTextureBindLayoutEntry,
    NormalizedBindLayoutEntry,
    NormalizedExternalTextureBindLayoutEntry,
    NormalizedSamplerBindLayoutEntry,
    NormalizedStorageBindLayoutEntry,
    NormalizedStorageTextureBindLayoutEntry,
    NormalizedTextureBindLayoutEntry,
    NormalizedUniformBindLayoutEntry,
    SamplerBindLayoutEntry,
    StorageBindLayoutEntry,
    StorageTextureBindLayoutEntry,
    TextureBindLayoutEntry,
    UniformBindLayoutEntry,
} from './gpu/binding.js'
export {
    LayoutCodec,
    createLayoutReadbackView,
    describeLayoutCompatibilityDifference,
    isLayoutArtifact,
    isLayoutBufferViewContract,
    isLayoutCodec,
    isLayoutUploadView,
    layoutArtifactAcceptsBindingByteLength,
    layoutArtifactAcceptsViewByteLength,
    layoutArtifactByteLength,
    layoutArtifactRuntimeElementCount,
    layoutArtifactsAbiCompatible,
    layoutArtifactsSchemaCompatible,
    layoutCodec,
} from './gpu/layout-codec.js'
export type {
    FixedLayoutArtifact,
    LayoutArtifact,
    LayoutArrayTypeArtifact,
    LayoutArrayTypeDescriptor,
    LayoutAtomicTypeArtifact,
    LayoutAtomicTypeDescriptor,
    LayoutBufferTypeDescriptor,
    LayoutBufferViewAccessMode,
    LayoutBufferViewAddressDescriptor,
    LayoutBufferViewAddressSpace,
    LayoutBufferViewBuiltin,
    LayoutBufferViewContract,
    LayoutBufferViewDescriptor,
    LayoutBufferViewPointerPath,
    LayoutBufferViewPointerDescriptor,
    LayoutCanonicalArrayTypeDescriptor,
    LayoutCanonicalAtomicTypeDescriptor,
    LayoutCanonicalBufferTypeDescriptor,
    LayoutCanonicalFieldDescriptor,
    LayoutCanonicalMatrixTypeDescriptor,
    LayoutCanonicalRuntimeArrayTypeDescriptor,
    LayoutCanonicalScalarTypeDescriptor,
    LayoutCanonicalSpec,
    LayoutCanonicalStructTypeDescriptor,
    LayoutCanonicalTypeDescriptor,
    LayoutCanonicalVectorTypeDescriptor,
    LayoutCapabilityContract,
    LayoutCodecOptions,
    LayoutCodecUsage,
    LayoutCompatibilityDifference,
    LayoutFieldArtifact,
    LayoutFieldDescriptor,
    LayoutFieldType,
    LayoutFixedFieldDescriptor,
    LayoutFixedFieldType,
    LayoutFixedBufferTypeArtifact,
    LayoutFixedStructTypeDescriptor,
    LayoutFixedStructTypeArtifact,
    LayoutMatrixDimension,
    LayoutMatrixType,
    LayoutMatrixTypeArtifact,
    LayoutMatrixTypeDescriptor,
    LayoutPackOptions,
    LayoutReadbackView,
    LayoutRuntimeArrayTypeArtifact,
    LayoutRuntimeArrayTypeDescriptor,
    LayoutRuntimeArrayFieldDescriptor,
    LayoutRuntimeBufferTypeArtifact,
    LayoutRuntimeExtent,
    LayoutRuntimeStructTypeArtifact,
    LayoutRuntimeStructTypeDescriptor,
    LayoutRuntimeTail,
    LayoutScalarType,
    LayoutScalarTypeArtifact,
    LayoutSpec,
    LayoutRootType,
    LayoutStructFields,
    LayoutStructSpec,
    LayoutStructTypeDescriptor,
    LayoutTypeArtifact,
    LayoutTypedSpec,
    LayoutTypeShorthand,
    LayoutUniformContract,
    LayoutUploadView,
    LayoutUsageCompatibility,
    LayoutUsageCompatibilityFact,
    LayoutValue,
    LayoutValues,
    LayoutVectorLength,
    LayoutVectorType,
    LayoutVectorTypeArtifact,
    LayoutVectorTypeDescriptor,
    LayoutWgslAccessorOptions,
    LayoutWgslBufferViewOptions,
    LayoutWriteOptions,
    RuntimeLayoutArtifact,
} from './gpu/layout-codec.js'
export { Program } from './gpu/program.js'
export type {
    ProgramBufferLayoutRequirement,
    ProgramDescriptor,
    ProgramStage,
} from './gpu/program.js'
export { ShaderModule } from './gpu/shader-module.js'
export type {
    NormalizedShaderModuleSourcePart,
    ShaderModuleCompilationHint,
    ShaderModuleCompilationHintFact,
    ShaderModuleCompilationHintLayout,
    ShaderModuleDescriptor,
    ShaderModuleSourcePart,
} from './gpu/shader-module.js'
export { inspectShader } from './gpu/shader-inspection.js'
export type {
    ShaderBindLayoutComparisonOptions,
    ShaderBinding,
    ShaderBindingResourceType,
    ShaderInspection,
    ShaderInspectionInput,
    ShaderInspectionOptions,
} from './gpu/shader-inspection.js'
export { ComputePipeline, RenderPipeline } from './gpu/pipeline.js'
export type { ComputePipelineDescriptor, RenderPipelineDescriptor } from './gpu/pipeline.js'
export { BeginOcclusionQueryCommand, ClearBufferCommand, CopyCommand, DispatchCommand, DrawCommand, EndOcclusionQueryCommand, ExternalImageUploadCommand, ReadbackCommand, ResolveQuerySetCommand, TextureUploadCommand, UploadCommand } from './gpu/command.js'
export type {
    BeginOcclusionQueryCommandDescriptor,
    ClearBufferCommandDescriptor,
    CommandBindSetInvocation,
    CommandImmediateData,
    CommandReadinessDescriptor,
    CommandResourceAccessDescriptor,
    CommandResourceReadDescriptor,
    CommandResourceReadEpoch,
    BufferCopyCommandSourceDescriptor,
    BufferToBufferCopyCommandDescriptor,
    BufferToTextureCopyCommandDescriptor,
    CopyCommandDescriptor,
    CopyCommandSourceDescriptor,
    DispatchCount,
    DispatchCommandDescriptor,
    DrawCount,
    DrawCommandDescriptor,
    DrawIndexBufferBinding,
    DrawRenderAttachmentExtent,
    DrawRenderState,
    DrawScissorRect,
    DrawVertexBufferBinding,
    DrawViewport,
    EndOcclusionQueryCommandDescriptor,
    ExternalImageUploadCommandDescriptor,
    ExternalImageUploadSize,
    ExternalImageUploadSourceOrigin,
    QuerySetSlotReadDescriptor,
    ReadbackCommandDescriptor,
    ReadbackCommandResultOptions,
    ResolveQuerySetCommandDescriptor,
    ResolveQuerySetSourceDescriptor,
    ResourceReadinessPolicy,
    IndirectCommandCount,
    StaticDispatchCount,
    StaticDrawCount,
    StaticIndexedDrawCount,
    SurfaceTextureCopyCommandSourceDescriptor,
    TextureCopyCommandSourceDescriptor,
    TextureCopyEndpointSourceDescriptor,
    TextureCopyOrigin,
    TextureCopySize,
    TextureToBufferCopyCommandDescriptor,
    TextureToTextureCopyCommandDescriptor,
    TexelCopyBufferLayout,
    TextureUploadCommandDescriptor,
    TextureUploadLayout,
    TextureUploadOrigin,
    TextureUploadSize,
    UploadCommandDescriptor,
} from './gpu/command.js'
export { DebugCommand } from './gpu/debug-command.js'
export type {
    DebugCommandAction,
    DebugCommandDescriptor,
} from './gpu/debug-command.js'
export {
    BundleDrawCommand,
    ExecuteRenderBundlesCommand,
    RenderBundle,
} from './gpu/render-bundle.js'
export type {
    BundleDrawCommandDescriptor,
    ExecuteRenderBundlesCommandDescriptor,
    RenderBundleCommand,
    RenderBundleDescriptor,
    RenderBundleLayout,
    RenderBundleRealization,
    RenderBundleRealizationState,
} from './gpu/render-bundle.js'
export { ComputePassSpec, RenderPassSpec } from './gpu/pass.js'
export type {
    ComputePassSpecDescriptor,
    RenderPassColorAttachmentSpec,
    RenderPassDepthStencilAttachmentSpec,
    RenderPassSpecDescriptor,
    TimestampWritesSpec,
} from './gpu/pass.js'
export { ReadbackOperation } from './gpu/readback.js'
export type {
    ReadbackOperationDescriptor,
    ReadbackRetentionPolicy,
    ReadbackSource,
    ReadbackState,
} from './gpu/readback.js'
export { MappedReadbackLease } from './gpu/readback-lease.js'
export type {
    MappedReadbackLeaseState,
} from './gpu/readback-lease.js'
export type {
    TextureReadbackOrigin,
    TextureReadbackRowLayout,
    TextureReadbackSize,
    TextureReadbackSource,
    TextureReadbackSourceDescriptor,
} from './gpu/texture-readback.js'
export { SubmissionBuilder, SubmittedWork } from './gpu/submission.js'
export type {
    ComputeCommand,
    RenderCommand,
    SubmittedPotentialWrite,
    SubmittedResourceEpoch,
    SubmissionBuilderOptions,
    SubmissionCommandExecutionOutcome,
    SubmissionCommandReadinessAttempt,
    SubmissionExecutionOutcome,
    SubmissionMissingResource,
    SubmissionPassExecutionOutcome,
    SubmittedReadbackLink,
    SubmittedRenderBundleFact,
    SubmissionResourceAccess,
    SubmissionResourceAccessKind,
    SubmissionStepKind,
    SubmissionValidationMode,
} from './gpu/submission.js'
